package com.cyberos.app.data

object BugBountyReportGenerator {

    fun toMarkdown(finding: BugBountyFinding, programName: String = ""): String {
        val sb = StringBuilder()
        sb.appendLine("# ${finding.title}")
        sb.appendLine()
        if (programName.isNotBlank()) sb.appendLine("**Program:** $programName")
        sb.appendLine("**Severity:** ${finding.severity}")
        sb.appendLine("**Status:** ${finding.status}")
        sb.appendLine("**Type:** ${finding.vulnerabilityType}")
        if (finding.asset.isNotBlank()) sb.appendLine("**Asset:** ${finding.asset}")
        if (finding.endpoint.isNotBlank()) sb.appendLine("**Endpoint:** `${finding.endpoint}`")
        sb.appendLine()
        sb.appendLine("## Summary")
        sb.appendLine(finding.description.ifBlank { "_No description yet._" })
        sb.appendLine()
        sb.appendLine("## Steps to Reproduce")
        sb.appendLine(finding.stepsToReproduce.ifBlank { "_Not provided._" })
        sb.appendLine()
        sb.appendLine("## Impact")
        sb.appendLine(finding.impact.ifBlank { "_Not provided._" })
        sb.appendLine()
        sb.appendLine("## Root Cause")
        sb.appendLine(finding.rootCause.ifBlank { "_Not provided._" })
        sb.appendLine()
        sb.appendLine("## Remediation")
        sb.appendLine(finding.remediation.ifBlank { "_Not provided._" })
        sb.appendLine()
        sb.appendLine("## Evidence")
        sb.appendLine(finding.evidenceNotes.ifBlank { "_No evidence notes._" })
        if (finding.linkedResearchIds.isNotEmpty()) {
            sb.appendLine()
            sb.appendLine("## Linked Research IDs")
            sb.appendLine(finding.linkedResearchIds.joinToString(", "))
        }
        sb.appendLine()
        sb.appendLine("---")
        sb.appendLine("_Generated by CyberOS — review before submission._")
        return sb.toString().trim() + "\n"
    }
}
